package org.papaja.commons.geo;

@SuppressWarnings({"SpellCheckingInspection"})
public enum Country {

    AF("Afghanistan", "افغانستان", "AF"),
    AL("Albania", "Shqipëria", "AL"),
    DZ("Algeria", "ⴷⵣⴰⵢⴻⵔ", "DZ"),
    AS("American Samoa", "Amerika Sāmoa", "AS"),
    AD("Andorra", "Andorra", "AD"),
    AO("Angola", "Ngola", "AO"),
    AQ("Antarctica", "Antarctica", "AQ"),
    AG("Antigua and Barbuda", "Antigua and Barbuda", "AG"),
    AR("Argentina", "Argentina", "AR"),
    AM("Armenia", "Հայաստան", "AM"),
    AW("Aruba", "Aruba", "AW"),
    AU("Australia", "Australia", "AU"),
    AT("Austria", "Österreich", "AT"),
    AZ("Azerbaijan", "Azərbaycan", "AZ"),
    BS("The Bahamas", "Bahamas", "BS"),
    BH("Bahrain", "البحرين", "BH"),
    BD("Bangladesh", "বাংলাদেশ", "BD"),
    BB("Barbados", "Barbados", "BB"),
    BY("Belarus", "Беларусь", "BY"),
    BE("Belgium", "Belgique", "BE"),
    BZ("Belize", "Belize", "BZ"),
    BJ("Benin", "Bénin", "BJ"),
    BM("Bermuda", "Bermuda", "BM"),
    BT("Bhutan", "འབྲུག་ཡུལ", "BT"),
    BO("Bolivia", "Buliwya", "BO"),
    BA("Bosnia and Herzegovina", "", "BA"),
    BW("Botswana", "Босна и Херцеговина", "BW"),
    BR("Brazil", "Brasil", "BR"),
    BN("Brunei", "بروني", "BN"),
    BG("Bulgaria", "България", "BG"),
    BF("Burkina Faso", "Burkina Faso", "BF"),
    BI("Burundi", "Uburundi", "BI"),
    KH("Cambodia", "កម្ពុជា", "KH"),
    CM("Cameroon", "Cameroon", "CM"),
    CA("Canada", "Canada", "CA"),
    CV("Cape Verde", "Cabo Verde", "CV"),
    KY("Cayman Islands", "Cayman Islands", "KY"),
    CF("Central African Republic", "Ködörösêse tî Bêafrîka", "CF"),
    TD("Chad", "تشاد", "TD"),
    CL("Chile", "Chile", "CL"),
    CN("China", "中国", "CN"),
    CX("Christmas Island", "Christmas Island", "CX"),
    CC("Cocos Islands", "Cocos Islands", "CC"),
    CO("Colombia", "Colombia", "CO"),
    KM("Comoros", "جزر القمر", "KM"),
    CG("Congo", "Republíki ya Kongó", "CG"),
    CR("Costa Rica", "Costa Rica", "CR"),
    CI("Côte d'Ivoire", "Côte d'Ivoire", "CI"),
    HR("Croatia", "Hrvatska", "HR"),
    CU("Cuba", "Cuba", "CU"),
    CY("Cyprus", "Κύπρος", "CY"),
    CZ("Czech Republic", "Česká republika", "CZ"),
    DK("Denmark", "Danmark", "DK"),
    DJ("Djibouti", "جيبوتي", "DJ"),
    DM("Dominica", "Dominica", "DM"),
    DO("Dominican Republic", "República Dominicana", "DO"),
    EC("ECUADOR", "Ecuador", "EC"),
    EG("Egypt", "مصر", "EG"),
    SV("El Salvador", "El Salvador", "SV"),
    GQ("Equatorial Guinea", "Guinea Ecuatorial", "GQ"),
    ER("Eritrea", "ኤርትራ", "ER"),
    EE("Estonia", "Eesti", "EE"),
    ET("Ethiopia", "ኢትዮጵያ", "ET"),
    FK("Falkland Islands", "Falkland Islands", "FK"),
    FO("Faroe Islands", "Føroyar", "FO"),
    FJ("Fiji", "Viti", "FJ"),
    FI("Finland", "Suomi", "FI"),
    FR("France", "France", "FR"),
    GF("French Guiana", "Guyane", "GF"),
    PF("French Polynesia", "Polynésie française", "PF"),
    GA("Gabon", "République gabonaise", "GA"),
    GM("The Gambia", "The Gambia", "GM"),
    GE("Georgia", "საქართველო", "GE"),
    DE("Germany", "Deutschland", "DE"),
    GH("Ghana", "Gaana", "GH"),
    GI("Gibraltar", "Gibraltar", "GI"),
    GR("Greece", "Ελλάδα", "GR"),
    GL("Greenland", "Kalaallit Nunaat", "GL"),
    GD("Grenada", "Grenada", "GD"),
    GP("Guadeloupe", "Guadeloupe", "GP"),
    GU("Guam", "Guåhån", "GU"),
    GT("Guatemala", "Guatemala", "GT"),
    GN("Guinea", "Gine", "GN"),
    GW("Guinea-Bissau", "Guiné-Bissau", "GW"),
    GY("Guyana", "Guyana", "GY"),
    HT("Haiti", "Ayiti", "HT"),
    HN("Honduras", "Honduras", "HN"),
    HK("Hong Kong", "香港", "HK"),
    HU("Hungary", "Magyarország", "HU"),
    IS("Iceland", "Ísland", "IS"),
    IN("India", "भारत", "IN"),
    ID("Indonesia", "Indonesia", "ID"),
    IR("Iran", "ایران", "IR"),
    IQ("Iraq", "العراق", "IQ"),
    IE("Ireland", "Ireland", "IE"),
    IL("Israel", "ישראל", "IL"),
    IT("Italy", "Italia", "IT"),
    JM("Jamaica", "Jamaica", "JM"),
    JP("Japan", "日本", "JP"),
    JO("Jordan", "الأردن", "JO"),
    KZ("Kazakhstan", "Қазақстан", "KZ"),
    KE("Kenya", "Kenya", "KE"),
    KI("Kiribati", "Kiribati", "KI"),
    KP("North Korea", "朝鮮", "KP"),
    KR("South Korea", "한국", "KR"),
    KW("Kuwait", "الكويت", "KW"),
    KG("Kyrgyzstan", "Кыргызстан", "KG"),
    LA("Laos", "ປະເທດລາວ", "LA"),
    LV("Latvia", "Latvija", "LV"),
    LB("Lebanon", "لبنان", "LB"),
    LS("Lesotho", "Lesotho", "LS"),
    LR("Liberia", "Liberia", "LR"),
    LI("Liechtenstein", "Liechtenstein", "LI"),
    LT("Lithuania", "Lietuva", "LT"),
    LY("Libya", "ليبيا", "LT"),
    LU("Luxembourg", "Lëtzebuerg", "LU"),
    MO("Macau", "澳門", "MO"),
    MK("Macedonia", "Северна Македонија", "MK"),
    MG("Madagascar", "Madagasikara", "MG"),
    MW("Malawi", "Malaŵi", "MW"),
    MY("Malaysia", "马来西亚", "MY"),
    MV("Maldives", "ދިވެހިރާއްޖެ", "MV"),
    ML("Mali", "Mali", "ML"),
    MT("Malta", "Malta", "MT"),
    MH("Marshall Islands", "Aorōkin M̧ajeļ", "MH"),
    MQ("Martinique", "Martinique", "MQ"),
    MR("Mauritania", "موريتانيا", "MR"),
    MU("Mauritius", "Moris", "MU"),
    YT("Mayotte", "Mayotte", "YT"),
    MX("Mexico", "México", "MX"),
    FM("Federated States of Micronesia", "Federated States of Micronesia", "FM"),
    MD("Moldova", "Moldova", "MD"),
    MC("Monaco", "Monaco", "MC"),
    MN("Mongolia", "Монгол Улс", "MN"),
    ME("Montenegro", "Црна Гора", "ME"),
    MS("Montserrat", "Montserrat", "MS"),
    MA("Morocco", "المغرب", "MA"),
    MZ("Mozambique", "Moçambique", "MZ"),
    MM("Myanmar", "မြန်မာ", "MM"),
    NA("Namibia", "Namibia", "NA"),
    NR("Nauru", "Naoero", "NR"),
    NP("Nepal", "नेपाल", "NP"),
    NL("Netherlands", "Nederland", "NL"),
    NC("New Caledonia", "Nouvelle-Calédonie", "NC"),
    NZ("New Zealand", "New Zealand", "NZ"),
    NI("Nicaragua", "Nicaragua", "NI"),
    NE("Niger", "Niger", "NE"),
    NG("Nigeria", "Nàìjíríà", "NG"),
    NU("Niue", "Niuē", "NU"),
    NF("Norfolk Island", "Norf'k Ailen", "NF"),
    NO("Norway", "Norge", "NO"),
    OM("Oman", "عُمان", "OM"),
    PK("Pakistan", "پاکستان", "PK"),
    PW("Palau", "Belau", "PW"),
    PS("Palestine", "فلسطين", "PS"),
    PA("Panama", "Panamá", "PA"),
    PG("Papua New Guinea", "Papua New Guinea", "PG"),
    PY("Paraguay", "Paraguay", "PY"),
    PE("Peru", "Perú", "PE"),
    PH("Philippines", "Pilipinas", "PH"),
    PL("Poland", "Polska", "PL"),
    PT("Portugal", "Portugal", "PT"),
    PR("Puerto Rico", "Puerto Rico", "PR"),
    QA("Qatar", "قطر", "QA"),
    RO("Romania", "România", "RO"),
    RU("Russia", "Россия", "RU"),
    RW("Rwanda", "Rwanda", "RW"),
    WS("Samoa", "Sāmoa", "WS"),
    SM("San Marino", "San Marino", "SM"),
    ST("São Tomé and Príncipe", "São Tomé e Príncipe", "ST"),
    SA("Saudi Arabia", "المملكة العربية السعودية", "SA"),
    SN("Senegal", "Sénégal", "SN"),
    RS("Serbia", "Србија", "RS"),
    SC("Seychelles", "Sesel", "SC"),
    SL("Sierra Leone", "Sierra Leone", "SL"),
    SG("Singapore", "新加坡", "SG"),
    SK("Slovakia", "Slovensko", "SK"),
    SI("Slovenia", "Slovenija", "SI"),
    SB("Solomon Islands", "Solomon Aelan", "SB"),
    SO("Somalia", "الصومال", "SO"),
    ZA("South Africa", "iNingizimu Afrika", "ZA"),
    ES("Spain", "España", "ES"),
    LK("Sri Lanka", "Sri Jayawardenapura Kotte", "LK"),
    SD("Sudan", "السودان", "SD"),
    SR("Suriname", "Suriname", "SR"),
    SE("Sweden", "Sverige", "SE"),
    CH("Switzerland", "Schweiz", "CH"),
    SY("Syria", "سورية", "SY"),
    TW("Taiwan", "臺灣", "TW"),
    TJ("Tajikistan", "Tojikistan", "TJ"),
    TZ("Tanzania", "Tanzania", "TZ"),
    TH("Thailand", "ราชอาณาจักรไทย", "TH"),
    TG("Togo", "Togo", "TG"),
    TO("Tonga", "Tonga", "TO"),
    TN("Tunisia", "تونس", "TN"),
    TR("Turkey", "Türkiye", "TR"),
    TM("Turkmenistan", "Türkmenistan", "TM"),
    TV("Tuvalu", "Tuvalu", "TV"),
    UG("Uganda", "Uganda", "UG"),
    UA("Ukraine", "Україна", "UA"),
    AE("UAE", "الإمارات العربيّة المتّحدة", "AE"),
    GB("United Kingdom", "United Kingdom", "GB"),
    US("United States", "USA", "US"),
    UY("Uruguay", "Uruguay", "UY"),
    UZ("Uzbekistan", "O‘zbekiston", "UZ"),
    VU("Vanuatu", "Vanuatu", "VU"),
    VE("Venezuela", "Venezuela", "VE"),
    VN("Vietnam", "Việt Nam", "VN"),
    YE("Yemen", "اليمن", "YE"),
    ZM("Zambia", "Zambia", "ZM"),
    ZW("Zimbabwe", "", "ZW");

    private String name;
    private String local;
    private String code;

    Country(String name, String local, String code) {
        this.name = name;
        this.local = local;
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public String getLocal() {
        return local;
    }

    public String getCode() {
        return code;
    }

    @Override
    public String toString() {
        return String.format("Country{name='%s', code='%s'}", name, code);
    }
}
